name : UnivNet_env
channels:
- defaults
dependencies :
  - python=3.6.1=2
  - numpy=1.12.1=py36_0
  - django=1.10.5=py36_0
  - openssl=1.0.2l=0
  - pip :
    - python-decouple
    - mysqlclient==1.3.10
    - social-auth-app-django==1.2.0